import pytest

from engine.pipeline.transform_engine import transform_text
from tests._policy_case import TextCase, assert_exact


POLICY_CASES = [
    # Counter-noun policy: hybrid-safe nouns use native only in the bounded range.
    TextCase(
        case_id="counter-hybrid-21-myeong",
        text="21명",
        expected="스물한 명",
        rule="counter noun / positive",
        reason="명 is hybrid-safe, so 21 must use the native form within the bounded range.",
    ),
    TextCase(
        case_id="counter-hybrid-22-gwon",
        text="22권",
        expected="스물두 권",
        rule="counter noun / positive",
        reason="권 is hybrid-safe, so 22 should use the native bounded-range form.",
    ),
    TextCase(
        case_id="counter-hybrid-23-jang",
        text="23장",
        expected="스물세 장",
        rule="counter noun / positive",
        reason="장 is hybrid-safe and must use the native form inside the safe range.",
    ),
    TextCase(
        case_id="counter-hybrid-20-special-smu",
        text="20명",
        expected="스무 명",
        rule="counter noun / boundary",
        reason="Twenty before a counter noun uses the special native form 스무.",
    ),
    TextCase(
        case_id="counter-hybrid-29-boundary",
        text="29명",
        expected="스물아홉 명",
        rule="counter noun / boundary",
        reason="Twenty-nine is the upper regular native boundary for hybrid-safe counters.",
    ),
    TextCase(
        case_id="counter-hybrid-30-special-boundary",
        text="30명",
        expected="서른 명",
        rule="counter noun / boundary",
        reason="Thirty is the last native special-case form before the sino fallback begins.",
    ),
    TextCase(
        case_id="counter-hybrid-31-sino-fallback",
        text="31명",
        expected="삼십일 명",
        rule="counter noun / fallback",
        reason="Thirty-one is outside the native safe range and must fall back to sino reading.",
    ),
    TextCase(
        case_id="counter-nonhybrid-57-gae-sino-fallback",
        text="57개",
        expected="오십칠 개",
        rule="counter noun / negative",
        reason="개 is hybrid-safe only up to 30, so 57 must use the sino fallback.",
    ),
    TextCase(
        case_id="counter-nonhybrid-floor-remains-sino",
        text="21층",
        expected="이십일 층",
        rule="counter noun / negative",
        reason="층 is sino-only and must not pick up the hybrid-safe native policy.",
    ),
    TextCase(
        case_id="counter-nonhybrid-won-remains-sino",
        text="21원",
        expected="이십일 원",
        rule="counter noun / negative",
        reason="원 is sino-only and must never use the hybrid-safe native reading.",
    ),
    # Currency policy: atomic parse with strict invalid-tail guards.
    TextCase(
        case_id="currency-prefix-symbol-krw",
        text="₩100",
        expected="백 원",
        rule="currency / positive",
        reason="KRW symbols may appear as a prefix and should normalize to 원.",
    ),
    TextCase(
        case_id="currency-suffix-code-krw",
        text="100 KRW",
        expected="백 원",
        rule="currency / positive",
        reason="KRW code suffixes are supported and normalize atomically as currency.",
    ),
    TextCase(
        case_id="currency-prefix-code-krw",
        text="KRW100",
        expected="백 원",
        rule="currency / positive",
        reason="A prefixed KRW code with no space is still a supported atomic currency pattern.",
    ),
    TextCase(
        case_id="currency-usd-decimal",
        text="$10.50",
        expected="십쩜오영 달러",
        rule="currency / decimal support",
        reason="USD is one of the currencies that explicitly supports decimal input.",
    ),
    TextCase(
        case_id="currency-eur-comma-decimal",
        text="€1,234.56",
        expected="천이백삼십사쩜오육 유로",
        rule="currency / atomic comma-decimal",
        reason="A comma decimal EUR pattern must be consumed atomically rather than partially by generic comma or decimal logic.",
    ),
    TextCase(
        case_id="currency-eur-prefix-code-comma-decimal",
        text="EUR1,234.56",
        expected="천이백삼십사쩜오육 유로",
        rule="currency / atomic comma-decimal",
        reason="A prefix currency code must support the same atomic comma-decimal behavior as a symbol prefix.",
    ),
    TextCase(
        case_id="currency-eur-suffix-code-comma-decimal",
        text="1,234.56 EUR",
        expected="천이백삼십사쩜오육 유로",
        rule="currency / atomic comma-decimal",
        reason="A suffix currency code must also parse atomically and produce the same reading.",
    ),
    TextCase(
        case_id="currency-yen-default-reading",
        text="¥100",
        expected="백 엔",
        rule="currency / default symbol mapping",
        reason="The base policy maps the yen symbol to 엔 unless a different currency context is explicitly defined.",
    ),
    TextCase(
        case_id="currency-pound-default-reading",
        text="£100",
        expected="백 파운드",
        rule="currency / positive",
        reason="A GBP symbol prefix is a supported currency pattern and normalizes to 파운드.",
    ),
    TextCase(
        case_id="currency-compact-krw-big-unit",
        text="10억 원",
        expected="십억 원",
        rule="currency / compact KRW",
        reason="Large Korean unit expressions with 원 stay in compact KRW reading rather than becoming generic digits.",
    ),
    TextCase(
        case_id="currency-compact-krw-decimal-big-unit",
        text="1.5조 원",
        expected="일조 오천억 원",
        rule="currency / compact KRW",
        reason="A decimal big-unit KRW expression must expand numerically and then reuse the large-number reading rules.",
    ),
    TextCase(
        case_id="currency-krw-decimal-not-supported",
        text="₩100.5",
        expected="₩100.5",
        rule="currency / guard",
        reason="KRW does not support decimal currency input and must stay original.",
    ),
    TextCase(
        case_id="currency-invalid-trailing-alpha-skip",
        text="300USDabc",
        expected="300USDabc",
        rule="currency / trailing alphabet guard",
        reason="An invalid alphabetic tail must cause the entire currency parse to skip without partial conversion.",
    ),
    TextCase(
        case_id="currency-invalid-code-extension-skip",
        text="300KRWa",
        expected="300KRWa",
        rule="currency / invalid code extension",
        reason="A code extension beyond the supported currency code boundary must block the entire parse.",
    ),
    TextCase(
        case_id="currency-invalid-prefix-code-skip",
        text="EURA 300",
        expected="EURA 300",
        rule="currency / invalid code extension",
        reason="An unsupported currency-code extension before the number must stay original.",
    ),
    TextCase(
        case_id="currency-negative-form-not-supported",
        text="$-10",
        expected="$-10",
        rule="currency / negative guard",
        reason="Negative currency input is not part of the supported currency policy and must not normalize as a currency.",
    ),
    # Unit policy: exact whitelist plus invalid-tail blocking.
    TextCase(
        case_id="unit-kmh",
        text="10km/h",
        expected="시속 십 킬로미터",
        rule="compound unit / positive",
        reason="km/h is on the exact whitelist and should render as 시속 plus the base unit.",
    ),
    TextCase(
        case_id="unit-ms",
        text="5m/s",
        expected="초속 오 미터",
        rule="compound unit / positive",
        reason="m/s is an exact whitelist compound and should render as 초속.",
    ),
    TextCase(
        case_id="unit-mmin",
        text="30m/min",
        expected="분속 삼십 미터",
        rule="compound unit / positive",
        reason="m/min is a supported compound unit and should render as 분속.",
    ),
    TextCase(
        case_id="unit-kml-decimal",
        text="15.2km/L",
        expected="리터당 십오쩜이 킬로미터",
        rule="compound unit / positive",
        reason="A decimal km/L form is supported and should render as 리터당 plus the normalized distance.",
    ),
    TextCase(
        case_id="unit-ml-simple-compound",
        text="3m/L",
        expected="리터당 삼 미터",
        rule="compound unit / positive",
        reason="m/L is on the exact whitelist and should render as 리터당 plus the normalized distance.",
    ),
    TextCase(
        case_id="unit-frequency-hz",
        text="60Hz",
        expected="육십 헤르츠",
        rule="frequency / positive",
        reason="Hz is a supported frequency unit and must parse before any generic acronym fallback.",
    ),
    TextCase(
        case_id="unit-frequency-ghz-decimal",
        text="2.4GHz",
        expected="이쩜사 기가헤르츠",
        rule="frequency / positive",
        reason="GHz is supported with decimals and should render as a normalized number plus the frequency unit.",
    ),
    TextCase(
        case_id="unit-geometry-square-meter",
        text="45㎡",
        expected="사십오 제곱미터",
        rule="geometry unit / positive",
        reason="The square-meter symbol is explicitly supported and should normalize to 제곱미터.",
    ),
    TextCase(
        case_id="unit-geometry-cubic-meter-caret-form",
        text="7m^3",
        expected="칠 세제곱미터",
        rule="geometry unit / positive",
        reason="The caret cubic-meter form is explicitly listed as a supported geometry unit variant.",
    ),
    TextCase(
        case_id="unit-single-letter-voltage-with-number",
        text="220V",
        expected="이백이십 볼트",
        rule="simple unit / positive",
        reason="A supported single-letter unit may normalize only when it has an explicit numeric prefix.",
    ),
    TextCase(
        case_id="unit-frequency-invalid-tail-skip",
        text="5Hzabc",
        expected="5Hzabc",
        rule="frequency / trailing alphabet guard",
        reason="A trailing alphabetic tail must block the full frequency parse without partial conversion.",
    ),
    TextCase(
        case_id="unit-kml-invalid-tail-skip",
        text="15.2km/La",
        expected="15.2km/La",
        rule="compound unit / trailing alphabet guard",
        reason="An invalid alphabetic tail after an otherwise supported compound unit must force a full skip.",
    ),
    TextCase(
        case_id="unit-unlisted-slash-compound-skip",
        text="3km/speed",
        expected="3km/speed",
        rule="compound unit / whitelist guard",
        reason="A slash compound outside the exact whitelist must remain original rather than partially normalizing the left side.",
    ),
    TextCase(
        case_id="unit-no-numeric-prefix-skip",
        text="km/L",
        expected="km/L",
        rule="compound unit / boundary",
        reason="Compound unit forms require a numeric prefix and must stay original without one.",
    ),
    TextCase(
        case_id="unit-unsupported-nested-compound-skip",
        text="3.14kg/m²",
        expected="3.14kg/m²",
        rule="compound unit / unsupported mixed format",
        reason="kg/m² is not in the supported exact slash whitelist and must skip as a whole.",
    ),
    # Special formats: pH, temperature, angle, acronym-special cases, and emergency numbers.
    TextCase(
        case_id="special-ph-positive",
        text="pH 7.0",
        expected="피에이치 칠쩜영",
        rule="pH / positive",
        reason="A clean pH expression is explicitly supported and should normalize as 피에이치 plus the decimal reading.",
    ),
    TextCase(
        case_id="special-ph-invalid-tail-skip-without-space",
        text="pH7.4test",
        expected="pH7.4test",
        rule="pH / partial-match guard",
        reason="Invalid tails on pH expressions must block the entire parse with no partial conversion.",
    ),
    TextCase(
        case_id="special-ph-invalid-tail-skip-with-space",
        text="pH 7.4a",
        expected="pH 7.4a",
        rule="pH / partial-match guard",
        reason="A trailing alphabet after the numeric pH value must cause a full skip.",
    ),
    TextCase(
        case_id="special-angle-positive",
        text="90°",
        expected="구십도",
        rule="angle / positive",
        reason="A numeric angle with the degree symbol is explicitly supported as 구십도.",
    ),
    TextCase(
        case_id="special-celsius-positive",
        text="25℃",
        expected="이십오도",
        rule="temperature / positive",
        reason="A Celsius-form temperature normalizes to a plain degree reading when there is no Fahrenheit marker.",
    ),
    TextCase(
        case_id="special-celsius-negative-uses-yeongha",
        text="-2.5℃",
        expected="영하 이쩜오도",
        rule="temperature / precedence",
        reason="Temperature-specific negative handling should use 영하 rather than the generic 마이너스 reading.",
    ),
    TextCase(
        case_id="special-fahrenheit-negative",
        text="-2.5℉",
        expected="화씨 영하 이쩜오도",
        rule="temperature / Fahrenheit",
        reason="A Fahrenheit temperature must preserve the 화씨 marker and still use temperature-specific negative handling.",
    ),
    TextCase(
        case_id="special-snp-dynamic-reading",
        text="S&P 500",
        expected="에스엔피 오백",
        rule="special acronym-number / positive",
        reason="S&P followed by a number is a special dynamic mapping, not generic acronym fallback plus number.",
    ),
    TextCase(
        case_id="special-snp-alternate-surface",
        text="SNP 500",
        expected="에스엔피 오백",
        rule="special acronym-number / positive",
        reason="SNP is treated as the same special surface as S&P for the dynamic numeric reading.",
    ),
    TextCase(
        case_id="special-d-number-protected",
        text="D-14",
        expected="D-14",
        rule="protection layer / D-number",
        reason="D-number identifiers are protected before rule parsing and must survive unchanged.",
    ),
    TextCase(
        case_id="special-emergency-context-positive-112",
        text="긴급번호 112는 경찰 신고 번호다",
        expected="긴급번호 일일이는 경찰 신고 번호다",
        rule="emergency number / positive context",
        reason="112 becomes the emergency reading only when context, boundary, and allowed tail conditions are all satisfied.",
    ),
    TextCase(
        case_id="special-emergency-context-positive-119",
        text="화재가 나면 119에 신고하세요",
        expected="화재가 나면 일일구에 신고하세요",
        rule="emergency number / positive context",
        reason="119 plus explicit emergency context and an allowed particle tail must convert to the emergency reading.",
    ),
    TextCase(
        case_id="special-emergency-general-number-fallback",
        text="회의실 번호는 112다",
        expected="회의실 번호는 백십이다",
        rule="emergency number / negative context",
        reason="Without emergency context, 112 is just a general number and must not use the emergency reading.",
    ),
    TextCase(
        case_id="special-emergency-disallowed-suffix-fallback",
        text="오늘 119건이 접수됐다",
        expected="오늘 백십구건이 접수됐다",
        rule="emergency number / disallowed suffix",
        reason="건 is not an allowed emergency tail, so 119 must fall back to the general numeric reading.",
    ),
    TextCase(
        case_id="special-emergency-general-number-with-myeong",
        text="112명 참석",
        expected="백십이명 참석",
        rule="emergency number / suffix guard",
        reason="명 is not an allowed emergency tail, so 112 must normalize as a general number plus suffix.",
    ),
    TextCase(
        case_id="special-emergency-embedded-token-negative",
        text="A112",
        expected="A112",
        rule="emergency number / boundary guard",
        reason="An embedded token boundary blocks emergency parsing and should also prevent partial numeric consumption.",
    ),
    TextCase(
        case_id="special-emergency-embedded-lowercase-negative",
        text="abc119",
        expected="abc119",
        rule="emergency number / boundary guard",
        reason="A number embedded inside an alphanumeric token must not be reinterpreted as an emergency number.",
    ),
    TextCase(
        case_id="special-emergency-context-but-disallowed-tail",
        text="긴급 신고는 112번으로 한다",
        expected="긴급 신고는 백십이번으로 한다",
        rule="emergency number / disallowed suffix",
        reason="Even with emergency context, 번 is not an allowed emergency tail so the token must fall back to the general reading.",
    ),
]


@pytest.mark.parametrize("case", POLICY_CASES, ids=lambda case: case.case_id)
def test_counter_currency_units_and_special_policy_matrix(case: TextCase):
    # These cases directly encode the source-of-truth policy for counters, currency, units, and special formats.
    assert_exact(transform_text(case.text), case)
