import pytest

from engine.pipeline.transform_engine import transform_text
from tests._policy_case import TextCase, assert_exact


NORMALIZATION_CASES = [
    TextCase(
        case_id="bracket-delete-parentheses-before-number-rules",
        text="안녕하세요(테스트)",
        expected="안녕하세요",
        rule="bracket handling / early cleanup",
        reason="A well-formed parenthesized span must be deleted before later numeric parsing.",
        classification="conflict",
    ),
    TextCase(
        case_id="bracket-keep-square-content-before-currency-rules",
        text="가격은 [₩1200]입니다",
        expected="가격은 천이백 원입니다",
        rule="bracket handling / early cleanup",
        reason="Square brackets keep inner content available for later normalization.",
        classification="override",
    ),
    TextCase(
        case_id="decimal-basic-contiguous",
        text="3.14",
        expected="삼쩜일사",
        rule="decimal / positive",
        reason="A contiguous digit-dot-digit pattern without higher-priority context is a standard decimal.",
        classification="conflict",
    ),
    TextCase(
        case_id="decimal-deep-fraction-within-limit",
        text="0.000125",
        expected="영쩜영영영일이오",
        rule="decimal / boundary",
        reason="A six-digit fractional part is still within the supported decimal limit.",
        classification="conflict",
    ),
    TextCase(
        case_id="decimal-fraction-over-limit-skips",
        text="12.0300405",
        expected="12.0300405",
        rule="decimal / guard",
        reason="More than six fractional digits exceed the supported decimal limit and must stay original.",
        classification="conflict",
    ),
    TextCase(
        case_id="decimal-comma-normalization-before-decimal-read",
        text="1,234.56",
        expected="천이백삼십사쩜오육",
        rule="decimal / preprocessing",
        reason="Thousands separators are removed before decimal parsing.",
        classification="conflict",
    ),
    TextCase(
        case_id="decimal-ambiguous-short-dotted-form-stays-original",
        text="12.12",
        expected="12.12",
        rule="decimal vs event ambiguity / negative",
        reason="A bare short dotted form remains ambiguous without an event keyword.",
        classification="conflict",
    ),
    TextCase(
        case_id="event-number-overrides-decimal",
        text="12.12 사태",
        expected="십이십이 사태",
        rule="event number / precedence",
        reason="An event keyword makes the dotted form an event phrase rather than a decimal.",
        classification="conflict",
    ),
    TextCase(
        case_id="dot-date-overrides-decimal",
        text="2025.01.03",
        expected="이천이십오년 일월 삼일",
        rule="date / precedence",
        reason="A full dotted date overrides generic decimal parsing.",
        classification="override",
    ),
    TextCase(
        case_id="ambiguous-dot-chain-skips-safely",
        text="12.12.1990",
        expected="12.12.1990",
        rule="date / guard",
        reason="An unsupported dotted chain must stay original.",
        classification="conflict",
    ),
    TextCase(
        case_id="year-month-short-dot-form-stays-original",
        text="2025.01",
        expected="2025.01",
        rule="decimal vs date ambiguity / guard",
        reason="A short year-month dotted form is ambiguous and must not fall back to decimal parsing.",
        classification="conflict",
    ),
    TextCase(
        case_id="middle-dot-date-like-two-block",
        text="7·25",
        expected="칠 이오",
        rule="middle dot structured / two-block date-like",
        reason="A 1-12 / 1-31 two-block middle-dot form uses Number Mode for the first block and Digit Mode for the second.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-date-like-two-block-ten-five",
        text="10·5",
        expected="십 오",
        rule="middle dot structured / two-block date-like",
        reason="A two-block date-like form still reads the first block as one number and the second block digit by digit.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-non-date-two-block",
        text="123·456",
        expected="일이삼 사오육",
        rule="middle dot structured / two-block digit mode",
        reason="A non-date-like two-block middle-dot form reads both blocks in Digit Mode.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-three-blocks-always-digit-mode",
        text="123·456·789",
        expected="일이삼 사오육 칠팔구",
        rule="middle dot structured / multi-block",
        reason="Three or more middle-dot blocks always read each block digit by digit.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-leading-zero-first-block",
        text="01·09",
        expected="공일 공구",
        rule="middle dot structured / leading zero",
        reason="Leading zero inside a structured middle-dot pattern triggers Digit Mode for the affected blocks.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-leading-zero-second-block",
        text="12·003",
        expected="일이 공공삼",
        rule="middle dot structured / leading zero",
        reason="A non-date-like second block with leading zeros remains in Digit Mode.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-spaced-pattern-preserves-symbol",
        text="123 · 456",
        expected="백이십삼 · 사백오십육",
        rule="middle dot structured / spacing guard",
        reason="Whitespace around the middle dot disables structured parsing and preserves the symbol while each side parses independently.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-edge-three-short-blocks",
        text="1·2·3",
        expected="일 이 삼",
        rule="middle dot structured / edge",
        reason="A three-block middle-dot pattern is not decimal or event syntax and keeps only the block boundaries.",
        classification="middle_dot",
    ),
    TextCase(
        case_id="middle-dot-bare-five-eighteen-is-not-event",
        text="5·18",
        expected="오 일팔",
        rule="middle dot structured / conflict",
        reason="A bare middle-dot form no longer behaves like an event-number parser input.",
        classification="conflict",
    ),
    TextCase(
        case_id="middle-dot-and-dot-difference",
        text="7.25",
        expected="칠쩜이오",
        rule="middle dot vs decimal / contrast",
        reason="A dot decimal and a middle-dot structured pattern must normalize differently.",
        classification="conflict",
    ),
    TextCase(
        case_id="digit-mode-leading-zero-007",
        text="007",
        expected="공공칠",
        rule="number mode / leading zero",
        reason="A bare leading-zero token uses Digit Mode.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="digit-mode-leading-zero-01",
        text="01",
        expected="공일",
        rule="number mode / leading zero",
        reason="A bare two-digit token with a leading zero uses Digit Mode.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="digit-mode-leading-zero-003",
        text="003",
        expected="공공삼",
        rule="number mode / leading zero",
        reason="A bare three-digit token with leading zeros uses Digit Mode.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="digit-mode-leading-zero-0001",
        text="0001",
        expected="공공공일",
        rule="number mode / leading zero",
        reason="A bare token with multiple leading zeros stays in Digit Mode across the whole token.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="override-date-month-beats-leading-zero",
        text="01월",
        expected="일월",
        rule="number mode / override date",
        reason="A date context forces Number Mode even when the token starts with zero.",
        classification="override",
    ),
    TextCase(
        case_id="override-date-day-beats-leading-zero",
        text="03일",
        expected="삼일",
        rule="number mode / override date",
        reason="A day token keeps Number Mode instead of Digit Mode.",
        classification="override",
    ),
    TextCase(
        case_id="override-time-hour-beats-leading-zero",
        text="09시",
        expected="아홉시",
        rule="number mode / override time",
        reason="An hour token with 시 keeps the time reading instead of Digit Mode.",
        classification="override",
    ),
    TextCase(
        case_id="override-time-hour-minute-beats-leading-zero",
        text="07시 05분",
        expected="일곱시 오분",
        rule="number mode / override time",
        reason="An explicit time expression keeps time readings for both hour and minute blocks.",
        classification="override",
    ),
    TextCase(
        case_id="override-currency-beats-leading-zero",
        text="₩01,000",
        expected="천 원",
        rule="number mode / override currency",
        reason="Currency parsing wins over leading-zero Digit Mode.",
        classification="override",
    ),
    TextCase(
        case_id="override-unit-beats-leading-zero",
        text="03kg",
        expected="삼 킬로그램",
        rule="number mode / override unit",
        reason="A supported unit suffix keeps Number Mode even when the numeric token starts with zero.",
        classification="override",
    ),
    TextCase(
        case_id="override-counter-beats-leading-zero",
        text="01명",
        expected="한 명",
        rule="number mode / override counter noun",
        reason="A counter-noun context keeps the hybrid counter reading instead of Digit Mode.",
        classification="override",
    ),
    TextCase(
        case_id="mixed-middle-dot-time-tail-stays-original",
        text="01·09시",
        expected="01·09시",
        rule="middle dot structured / mixed guard",
        reason="A middle-dot numeric core with an attached time suffix must not partially normalize.",
        classification="conflict",
    ),
    TextCase(
        case_id="mixed-middle-dot-unit-tail-stays-original",
        text="12·003kg",
        expected="12·003kg",
        rule="middle dot structured / mixed guard",
        reason="A middle-dot numeric core with an attached unit suffix must not partially normalize.",
        classification="conflict",
    ),
    TextCase(
        case_id="mixed-identifier-leading-zero-digit-mode",
        text="ID: 00123",
        expected="아이디 공공일이삼",
        rule="number mode / identifier digit mode",
        reason="An identifier context should switch the numeric payload to Digit Mode and keep the identifier reading fixed.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="mixed-phone-hyphen-digit-blocks",
        text="010-1234-5678",
        expected="공일공 일이삼사 오육칠팔",
        rule="number mode / phone digit blocks",
        reason="Phone-like hyphen blocks read digit by digit by block.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="hyphen-date-priority",
        text="2026-04-17",
        expected="이천이십육년 사월 십칠일",
        rule="date / hyphen precedence",
        reason="A YYYY-MM-DD form is a date, not a generic hyphen block.",
        classification="override",
    ),
    TextCase(
        case_id="hyphen-multi-block-code-reading",
        text="12-34-56",
        expected="일이 삼사 오육",
        rule="hyphen digit blocks / positive",
        reason="Three numeric hyphen blocks read block by block in Digit Mode.",
        classification="digit_mode",
    ),
    TextCase(
        case_id="generic-two-block-hyphen-stays-original",
        text="1-2",
        expected="1-2",
        rule="hyphen protection / negative",
        reason="A generic two-block hyphen form stays original.",
        classification="conflict",
    ),
    TextCase(
        case_id="fraction-basic",
        text="1/3",
        expected="삼분의 일",
        rule="fraction / positive",
        reason="A clean slash fraction without date context normalizes as a fraction.",
        classification="conflict",
    ),
    TextCase(
        case_id="slash-date-overrides-fraction",
        text="2024/01/01",
        expected="이천이십사년 일월 일일",
        rule="date / slash precedence",
        reason="A full slash date overrides fraction parsing.",
        classification="override",
    ),
    TextCase(
        case_id="hhmm-positive-schedule-context",
        text="회의는 12:30에 시작한다",
        expected="회의는 열두시 삼십분에 시작한다",
        rule="HH:MM / positive context",
        reason="A time particle plus schedule verb creates explicit HH:MM time context.",
        classification="override",
    ),
    TextCase(
        case_id="hhmm-standalone-stays-original",
        text="12:30",
        expected="12:30",
        rule="HH:MM / standalone guard",
        reason="A bare HH:MM token remains ambiguous without time context.",
        classification="conflict",
    ),
    TextCase(
        case_id="independent-time-with-afternoon-marker",
        text="오후 2시 본회의",
        expected="오후 두시 본회의",
        rule="time / independent H시",
        reason="An independent H시 form with an afternoon marker is always time.",
        classification="override",
    ),
    TextCase(
        case_id="independent-time-with-josa-binding",
        text="오늘 밤 11시부터",
        expected="오늘 밤 열한시부터",
        rule="time + phonetic binding / positive",
        reason="An explicit H시 form followed by a time particle stays bound as one time phrase.",
        classification="override",
    ),
]


@pytest.mark.parametrize("case", NORMALIZATION_CASES, ids=lambda case: case.case_id)
def test_numeric_datetime_policy_matrix(case: TextCase):
    assert_exact(transform_text(case.text), case)
